{{- if .Values.serviceAccounts.sparkoperator.create }}
{{- range $isDeleteHook := until 2 }}
{{- with $ }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-operator.serviceAccountName" . }}
  annotations:
    {{- if eq $isDeleteHook 0 }}
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed
    {{- else }}
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    "helm.sh/hook-weight": "-10"
{{- with .Values.serviceAccounts.sparkoperator.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
